# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Chao Zhang's Lab
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Website of the Chao Zhang's Lab.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

# Files and folders excluded from the generated website
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  # 网站不需要打包的备份、压缩包和高清原图
  - images/teampic/teampic.rar
  - images/teampic/PIC_v2.0.zip
  - images/teampic2/PIC_v2.0.zip
  - images/publication-covers-original
  - images/slides

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
